name: Run Sync Script

on:
  push:
    branches:
      - main-polis

jobs:
  run_sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"

      - name: Set up Python
        run: uv python install

      - name: Run sync script
        env:
          BSKY_SYNC_CONFIG_FILE: "accounts.polis.txt"
          AT_LOGIN: "patcon.bsky.social"
          AT_PASSWORD: ${{ secrets.AT_PASSWORD }}
          STARTER_PACK_URI: "at://patcon.bsky.social/app.bsky.graph.starterpack/3laxcisdajc2n"
          LIST_URI: "at://did:plc:k7f2fckeefeh7mcohlezhpbn/app.bsky.graph.list/3lcqrsp3juf2b"
        run: uv run sync.py
